// Prueba de la migración 021 contra una base local (PGlite: Postgres real en
// WebAssembly, sin instalar nada) y de las reglas del correo a cualquier
// ciudad: zonas por distancia, direcciones de otra ciudad, código postal y
// seguimiento. No toca Supabase ni ninguna base real.
//
//   npm run probar:021
//
// La base imita producción en lo que importa acá (resultados del 4/10/2026):
// las columnas de direcciones, sus dos disparadores, los permisos de anon y
// authenticated (tabla y columnas, incluido TRUNCATE), la tienda 15 con
// precios de correo por provincia y envio_zona_fallas como la dejó la 019.
// Lo que NO prueba: RLS ni PostgREST.

import { PGlite } from "@electric-sql/pglite"
import { readFileSync } from "node:fs"
import { register } from "node:module"

// Node no conoce el alias '@/' de jsconfig.json: se resuelve a src/.
const raiz = new URL("../", import.meta.url)
register("data:text/javascript," + encodeURIComponent(`
const src = ${JSON.stringify(new URL("src/", raiz).href)}
export function resolve(especificador, contexto, siguiente) {
  if (especificador.startsWith('@/')) {
    const ruta = src + especificador.slice(2)
    return siguiente(/\\.[a-z]+$/.test(ruta) ? ruta : ruta + '.js', contexto)
  }
  return siguiente(especificador, contexto)
}
`))

const L = await import("../src/lib/metodosEntrega.js")
const D = await import("../src/lib/direcciones.js")
const { calcularEnvio } = await import("../src/lib/precioPedido.js")
const { zonasPara } = await import("../src/lib/zonaEnvio.js")

const leer = (f) => readFileSync(new URL(`../sql/migrations/${f}`, import.meta.url), "utf8")
const M021 = leer("021_correo_ciudades.sql")
const M019 = leer("019_envio_zona.sql")
const M017 = leer("017_localidades_activa.sql")
const M006 = leer("006_vendedores_vuelta_a_revision.sql")

let fallas = 0
const ok = (cond, msg) => { if (!cond) { fallas++; console.log("  ✗ FALLA:", msg) } else console.log("  ✓", msg) }
const igual = (a, b) => JSON.stringify(a) === JSON.stringify(b)
const q = async (db, sql, p) => (await db.query(sql, p)).rows

async function como(db, rol, sql) {
  try {
    await db.exec(`set role ${rol}`)
    await db.query(sql)
    return null
  } catch (e) {
    return e.message
  } finally {
    await db.exec("reset role")
  }
}
const negado = (e) => !!e && /permission denied/.test(e)

const COLUMNAS_VIEJAS = ["id", "usuario_id", "etiqueta", "calle", "numero", "piso_depto", "barrio_id",
  "referencia", "telefono", "lat", "lng", "es_principal", "creada_en"]

async function baseNueva(tipoCostos = "jsonb") {
  const db = new PGlite()
  await db.exec(`
  create role anon; create role authenticated; create role service_role bypassrls;
  create schema privado;
  grant usage on schema privado to anon, authenticated, service_role;

  create table public.localidades (id serial primary key, nombre text);
  insert into public.localidades (nombre) values ('Bahía Blanca'), ('Ingeniero White'), ('General Daniel Cerri');
  create table public.barrios (id serial primary key, nombre text, localidad_id int, es_oficial boolean default true, poligono text);
  insert into public.barrios (nombre, localidad_id) values ('Centro', 1), ('Universitario', 1);

  create table public.vendedores (
    id serial primary key, nombre_negocio text, localidad_id int, barrio_id int,
    estado_validacion text default 'aprobado',
    metodos_entrega_default text[] not null default '{}',
    costos_envio_zona ${tipoCostos} not null default '{}'
  );
  insert into public.vendedores (id, nombre_negocio, localidad_id, barrio_id, estado_validacion, metodos_entrega_default, costos_envio_zona) values
    (14, 'Catorce', 1, 1, 'aprobado', '{retiro,envio_tienda}', '{"zona_1": 500, "zona_2": 900}'),
    (15, 'Ludoméstica', 1, 2, 'necesita_cambios', '{retiro,correo}',
         '{"correo_1": 4000, "correo_2": 5000, "correo_3": 6000, "correo_4": 7000, "zona_1": 0}'),
    (16, 'Dieciséis', 1, 1, 'aprobado', '{coordinar}', '{}');

  create table public.direcciones (
    id bigint generated by default as identity primary key,
    usuario_id uuid not null, etiqueta text, calle text not null, numero text not null,
    piso_depto text, barrio_id bigint, referencia text, telefono text not null,
    lat float8, lng float8, es_principal bool not null default false,
    creada_en timestamptz not null default now()
  );
  insert into public.direcciones (usuario_id, calle, numero, barrio_id, telefono, lat, lng) values
    (gen_random_uuid(), 'Alsina', '235', 1, '2915123456', -38.7183, -62.2663),
    (gen_random_uuid(), 'Donado', '80', 2, '2915000000', -38.71, -62.27),
    (gen_random_uuid(), 'Chiclana', '9', 1, '2915111111', -38.72, -62.26);

  -- El disparador de cuentas cerradas (016), con una función que no hace nada.
  create function privado.rechazar_cuenta_cerrada() returns trigger language plpgsql as $$ begin return new; end; $$;
  create trigger rechazar_cuenta_cerrada before insert on public.direcciones
    for each row execute function privado.rechazar_cuenta_cerrada('usuario_id');

  -- Permisos como en producción: todo a nivel de tabla y, además, INSERT,
  -- REFERENCES, SELECT y UPDATE en cada columna, para anon y authenticated.
  grant all on public.direcciones to anon, authenticated;
  grant insert (${COLUMNAS_VIEJAS.join(", ")}), references (${COLUMNAS_VIEJAS.join(", ")}),
        select (${COLUMNAS_VIEJAS.join(", ")}), update (${COLUMNAS_VIEJAS.join(", ")})
    on public.direcciones to anon, authenticated;
  grant all on public.direcciones to service_role;

  create table public.pedidos (id bigserial primary key, vendedor_id bigint, metodo_envio text, estado text, zona_envio smallint);
  insert into public.pedidos (vendedor_id, metodo_envio, estado) select 14, 'retiro', 'despachado' from generate_series(1, 16);
  `)
  await db.exec(M006)
  await db.exec(M017)
  // La 019 tal cual (sus funciones de barrios usan PostGIS: no se validan acá).
  await db.exec("set check_function_bodies = off")
  await db.exec(M019)
  await db.exec("reset check_function_bodies")
  await db.exec(`insert into public.envio_zona_fallas (vendedor_id, direccion_id, motivo, origen) values (14, 1, 'direccion_sin_punto', 'cotizar')`)
  return db
}

async function foto(db) {
  return JSON.stringify((await q(db, `select json_build_object(
    'columnas', (select json_agg(json_build_object('t', c.relname, 'n', a.attname, 'tipo', format_type(a.atttypid, a.atttypmod),
                  'nulo', not a.attnotnull, 'def', pg_get_expr(d.adbin, d.adrelid)) order by c.relname, a.attnum)
                 from pg_attribute a join pg_class c on c.oid = a.attrelid
                 left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
                 where c.relname in ('direcciones', 'pedidos', 'envio_zona_fallas', 'vendedores') and c.relnamespace = 'public'::regnamespace
                   and a.attnum > 0 and not a.attisdropped),
    'constraints', (select json_agg(json_build_object('n', conname, 'd', pg_get_constraintdef(oid)) order by conname)
                 from pg_constraint where conrelid in ('public.direcciones'::regclass, 'public.pedidos'::regclass, 'public.envio_zona_fallas'::regclass)),
    'disparadores', (select json_agg(json_build_object('t', tgrelid::regclass::text, 'n', tgname, 'on', tgenabled) order by 1)
                 from pg_trigger where tgrelid in ('public.direcciones'::regclass, 'public.vendedores'::regclass) and not tgisinternal),
    'acl', (select array_to_string(array(select x::text from unnest(relacl) x order by 1), ',') from pg_class where oid = 'public.direcciones'::regclass),
    'acl_columnas', (select json_agg(json_build_object('n', attname, 'a', array_to_string(array(select x::text from unnest(attacl) x order by 1), ',')) order by attnum)
                 from pg_attribute where attrelid = 'public.direcciones'::regclass and attnum > 0 and not attisdropped),
    'direcciones', (select json_agg(d order by id) from public.direcciones d),
    'vendedores', (select json_agg(json_build_object('id', id, 'c', costos_envio_zona::jsonb, 'e', estado_validacion) order by id) from public.vendedores),
    'fallas', (select json_agg(f order by id) from public.envio_zona_fallas f)
  ) as f`))[0].f)
}

// ═══════════════════════════════════════════════════════════════════════════
console.log("\n1. La 021 corre dos veces")
const db = await baseNueva()
await db.exec(M021)
const foto1 = await foto(db)
await db.exec(M021)
ok(foto1 === await foto(db), "la segunda corrida no cambia nada")

console.log("\n2. Direcciones: columnas, relleno y CHECK")
{
  const cols = (await q(db, `select attname from pg_attribute where attrelid = 'public.direcciones'::regclass and attnum > 0 and not attisdropped order by attnum`)).map((r) => r.attname)
  ok(igual(cols.slice(-3), ["ciudad", "provincia", "codigo_postal"]), "ciudad, provincia y codigo_postal")
  const filas = await q(db, `select ciudad, provincia, codigo_postal from public.direcciones order by id`)
  ok(filas.every((f) => f.ciudad === "Bahía Blanca" && f.provincia === "Buenos Aires" && f.codigo_postal === null),
    "las 3 direcciones (con barrio) quedan en Bahía Blanca, Buenos Aires, sin código postal inventado")

  const ins = (cols) => como(db, "postgres", `insert into public.direcciones (usuario_id, calle, numero, telefono, ${Object.keys(cols).join(", ")})
    values (gen_random_uuid(), 'X', '1', '1', ${Object.values(cols).map((v) => v === null ? "null" : `'${v}'`).join(", ")})`)
  for (const p of D.PROVINCIAS) ok(await ins({ provincia: p }) === null, `acepta la provincia ${p} (la lista de JS)`)
  ok(!!(await ins({ provincia: "Patagonia" })), "rechaza una provincia que no está en la lista")
  ok(!!(await ins({ ciudad: "" })), "rechaza una ciudad vacía")
  ok(!!(await ins({ ciudad: "x".repeat(81) })), "rechaza una ciudad de más de 80 caracteres")

  // El formato del código postal: lo mismo en JS y en la base.
  const muestras = ["8000", "B8000ABC", "b8000abc", "B 8000 ABC", "800", "80000", "B8000AB", "ABCD", "8000-ABC", "C1043AAZ", ""]
  for (const m of muestras) {
    const normal = D.normalizarCodigoPostal(m)
    const base = normal === "" ? false : (await ins({ codigo_postal: normal })) === null
    ok(base === D.codigoPostalValido(m), `código postal "${m}" → "${normal}": la base y JS coinciden (${base ? "vale" : "no vale"})`)
  }
  ok(!!(await ins({ codigo_postal: "b8000abc" })), "la base exige el código ya normalizado (mayúsculas, sin espacios)")
}

console.log("\n3. Disparadores")
{
  const t = await q(db, `select tgrelid::regclass::text as tabla, tgname from pg_trigger where not tgisinternal and tgrelid in ('public.direcciones'::regclass, 'public.vendedores'::regclass) order by 1, 2`)
  ok(igual(t.filter((r) => r.tabla === "direcciones").map((r) => r.tgname), ["rechazar_cuenta_cerrada"]),
    "direcciones: sólo queda rechazar_cuenta_cerrada")
  ok(t.some((r) => r.tabla === "vendedores" && r.tgname === "rechazar_localidad_inactiva"), "vendedores: sigue rechazar_localidad_inactiva")
  await db.exec(`update public.localidades set activa = false where id = 2`)
  ok(!!(await como(db, "postgres", `update public.vendedores set localidad_id = 2 where id = 14`)), "y sigue funcionando en vendedores")
}

console.log("\n4. Permisos de direcciones")
{
  const columnas = (await q(db, `select attname from pg_attribute where attrelid = 'public.direcciones'::regclass and attnum > 0 and not attisdropped order by attnum`)).map((r) => r.attname)
  const tabla = await q(db, `select p, has_table_privilege('anon', 'public.direcciones', p) as anon, has_table_privilege('authenticated', 'public.direcciones', p) as aut
    from unnest(array['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER']) p`)
  ok(tabla.every((r) => !r.anon), "anon: ningún permiso de tabla")
  const anonCol = await q(db, `select count(*)::int as n from information_schema.column_privileges where table_name = 'direcciones' and grantee = 'anon'`)
  ok(anonCol[0].n === 0, "anon: ningún permiso de columna")
  for (const col of columnas) {
    const r = (await q(db, `select has_column_privilege('anon', 'public.direcciones', $1, 'SELECT') as s, has_column_privilege('anon', 'public.direcciones', $1, 'UPDATE') as u`, [col]))[0]
    if (r.s || r.u) ok(false, `anon todavía puede leer o editar ${col}`)
  }
  ok(negado(await como(db, "anon", `select * from public.direcciones`)), "anon no lee direcciones")
  ok(negado(await como(db, "anon", `truncate public.direcciones`)), "anon no vacía la tabla")

  const aut = Object.fromEntries(tabla.map((r) => [r.p, r.aut]))
  ok(aut.SELECT && aut.INSERT && aut.UPDATE && aut.DELETE, "authenticated: sigue con SELECT, INSERT, UPDATE y DELETE")
  ok(!aut.TRUNCATE && !aut.REFERENCES && !aut.TRIGGER, "authenticated: sin TRUNCATE, REFERENCES ni TRIGGER")
  ok(negado(await como(db, "authenticated", `truncate public.direcciones`)), "authenticated no vacía la tabla")
  const refCol = await q(db, `select count(*)::int as n from information_schema.column_privileges where table_name = 'direcciones' and grantee = 'authenticated' and privilege_type = 'REFERENCES'`)
  ok(refCol[0].n === 0, "authenticated: sin REFERENCES en ninguna columna")
  for (const col of ["ciudad", "provincia", "codigo_postal"]) {
    const r = (await q(db, `select has_column_privilege('authenticated', 'public.direcciones', $1, 'SELECT') s,
      has_column_privilege('authenticated', 'public.direcciones', $1, 'INSERT') i, has_column_privilege('authenticated', 'public.direcciones', $1, 'UPDATE') u,
      has_column_privilege('anon', 'public.direcciones', $1, 'SELECT') anon`, [col]))[0]
    ok(r.s && r.i && r.u && !r.anon, `${col}: SELECT, INSERT y UPDATE para authenticated; nada para anon`)
  }
  ok(await como(db, "authenticated", `insert into public.direcciones (usuario_id, calle, numero, telefono, ciudad, provincia, codigo_postal, lat, lng)
    values (gen_random_uuid(), 'Colón', '10', '2932000000', 'Punta Alta', 'Buenos Aires', 'B8109ABC', -38.88, -62.07)`) === null,
    "el formulario (authenticated) guarda una dirección de otra ciudad")
  ok(await como(db, "authenticated", `update public.direcciones set codigo_postal = '8000' where id = 1`) === null,
    "y le agrega el código postal a una vieja (checkout)")
  ok(await como(db, "service_role", `select ciudad, codigo_postal from public.direcciones`) === null, "service_role (las rutas) lee todo")
}

console.log("\n5. Seguimiento en pedidos")
{
  const pone = (empresa, otra, numero) => como(db, "postgres", `update public.pedidos set envio_empresa = ${empresa}, envio_empresa_otra = ${otra}, envio_seguimiento = ${numero} where id = 1`)
  ok(await pone("'andreani'", "null", "'360000123'") === null, "Andreani con número")
  ok(await pone("'otra'", "'Vía Cargo'", "'VC-1'") === null, "otra empresa con nombre y número")
  ok(await pone("null", "null", "null") === null, "sin seguimiento")
  ok(!!(await pone("'dhl'", "null", "'1'")), "rechaza una empresa que no está en la lista")
  ok(!!(await pone("'oca'", "null", "null")), "rechaza empresa sin número")
  ok(!!(await pone("null", "null", "'123'")), "rechaza número sin empresa")
  ok(!!(await pone("'otra'", "null", "'1'")), "rechaza 'otra' sin nombre")
  ok(!!(await pone("'oca'", "'Algo'", "'1'")), "rechaza un nombre con una empresa conocida")
  ok(!!(await pone("'oca'", "null", `'${"9".repeat(61)}'`)), "rechaza un número de más de 60")
  for (const empresa of Object.keys(L.EMPRESAS_ENVIO)) {
    const otra = empresa === "otra" ? "'X'" : "null"
    ok(await pone(`'${empresa}'`, otra, "'1'") === null, `acepta ${empresa} (la lista de JS)`)
  }
}

console.log("\n6. envio_zona_fallas.metodo")
{
  ok((await q(db, `select metodo from public.envio_zona_fallas where id = 1`))[0].metodo === "envio_tienda", "la fila que había queda como envío de la tienda")
  ok(await como(db, "service_role", `insert into public.envio_zona_fallas (vendedor_id, motivo, metodo, origen) values (15, 'tienda_sin_punto', 'correo', 'crear')`) === null, "acepta 'correo'")
  ok(!!(await como(db, "service_role", `insert into public.envio_zona_fallas (motivo, metodo, origen) values ('tienda_sin_punto', 'retiro', 'crear')`)), "rechaza otro método")
}

console.log("\n7. Precios de correo")
{
  const v = Object.fromEntries((await q(db, `select id, costos_envio_zona::jsonb as c, estado_validacion as e, metodos_entrega_default as m from public.vendedores`)).map((r) => [r.id, r]))
  ok(igual(v[15].c, { zona_1: 0 }), "tienda 15: sin correo_1..4, conserva zona_1")
  ok(igual(v[15].m, ["retiro", "correo"]), "tienda 15: el correo sigue tildado")
  ok(L.correoSinPrecios({ metodos_entrega_default: v[15].m, costos_envio_zona: v[15].c }), "…así que el panel le muestra el aviso")
  ok(v[15].e === "necesita_cambios", "tienda 15: no volvió a revisión (006 apagada mientras dura)")
  ok(igual(v[14].c, { zona_1: 500, zona_2: 900 }), "tienda 14: sus precios del envío de la tienda, intactos")
  ok((await q(db, `select tgenabled from pg_trigger where tgname = 'trg_vendedores_vuelta_a_revision'`))[0].tgenabled === "O", "la 006 quedó prendida")

  const conJson = await baseNueva("json")
  await conJson.exec(M021)
  await conJson.exec(M021)
  ok(igual((await q(conJson, `select costos_envio_zona::jsonb as c from public.vendedores where id = 15`))[0].c, { zona_1: 0 }),
    "con costos_envio_zona json también: se borran los de correo")
}

// ═══════════════════════════════════════════════════════════════════════════
const CIUDADES = {
  bahia: { lat: -38.7183, lng: -62.2663 },
  "Punta Alta": { lat: -38.8796, lng: -62.0753 }, "Ingeniero White": { lat: -38.7833, lng: -62.2667 },
  "General Daniel Cerri": { lat: -38.7136, lng: -62.3931 }, "Médanos": { lat: -38.8285, lng: -62.6948 },
  "Monte Hermoso": { lat: -38.9833, lng: -61.3 }, "Tornquist": { lat: -38.1004, lng: -62.2214 },
  "Coronel Pringles": { lat: -37.9827, lng: -61.3539 }, "Coronel Dorrego": { lat: -38.7187, lng: -61.2873 },
  "Tres Arroyos": { lat: -38.377, lng: -60.2753 }, "Viedma": { lat: -40.8135, lng: -62.9967 },
  "Santa Rosa": { lat: -36.6203, lng: -64.2906 }, "Tandil": { lat: -37.3217, lng: -59.1332 },
  "Mar del Plata": { lat: -38.0055, lng: -57.5426 }, "Ciudad de Buenos Aires": { lat: -34.6037, lng: -58.3816 },
  "Rosario": { lat: -32.9468, lng: -60.6393 }, "Córdoba": { lat: -31.4201, lng: -64.1888 }, "Mendoza": { lat: -32.8895, lng: -68.8458 },
}

console.log("\n8. Zonas del correo por distancia (desde el centro de Bahía)")
{
  ok(igual(L.ZONAS_CORREO.map((z) => z.hastaMetros), [50000, 150000, 500000, null]), "cortes: 50, 150 y 500 km, y más")
  ok(igual(L.ZONAS_CORREO.map((z) => z.nombre), ["Hasta 50 km", "Hasta 150 km", "Hasta 500 km", "Más de 500 km"]), "nombres para la tienda")
  for (const zona of L.ZONAS_CORREO) {
    const nombres = zona.ejemplos.split(", ").map((n) => (n === "General Daniel Cerri" ? n : n))
    for (const ciudad of nombres) {
      const punto = CIUDADES[ciudad]
      if (!punto) { ok(false, `falta el punto de ${ciudad} en la prueba`); continue }
      const km = Math.round(L.distanciaRectaMetros(CIUDADES.bahia, punto) / 1000)
      ok(L.zonaCorreoEntrePuntos(CIUDADES.bahia, punto) === zona.zona, `${ciudad} (~${km} km): zona ${zona.zona}, como dice el ejemplo`)
    }
  }
  ok(L.zonaCorreoEntrePuntos(CIUDADES.bahia, { lat: null, lng: null }) === null, "sin punto: null")
  ok(L.zonaCorreoEntrePuntos(CIUDADES.bahia, CIUDADES.bahia) === 1, "la misma Bahía: zona 1")
}

console.log("\n9. Envío de la tienda: hasta 20 km, sea la ciudad que sea")
{
  const zona = (ciudad) => L.zonaEntrePuntos(CIUDADES.bahia, CIUDADES[ciudad])
  ok(zona("Ingeniero White") === 4, "Ingeniero White (~7 km rectos, ~9 por calles): zona 4 si la tienda le pone precio")
  ok(zona("General Daniel Cerri") === 4, "General Daniel Cerri (~11 km rectos, ~14 por calles): zona 4")
  ok(zona("Punta Alta") === null, "Punta Alta (~24 km rectos): no llega")
  ok(zona("Médanos") === null, "Médanos: no llega")
}

console.log("\n10. Qué ve quien compra (envío de la tienda × correo)")
{
  const t = (metodos, costos) => ({ metodos_entrega_default: metodos, costos_envio_zona: costos })
  const ambos = t(["envio_tienda", "correo"], { zona_1: 500, zona_4: 2000, correo_1: 3000, correo_4: 9000 })

  let r = L.metodosParaComprador(ambos, { zonaTienda: 1, zonaCorreo: 1 })
  ok(igual(r.disponibles, ["envio_tienda", "correo"]), "dirección de Bahía: envío de la tienda y correo zona 1")
  r = L.metodosParaComprador(ambos, { zonaTienda: null, zonaCorreo: 4 })
  ok(igual(r.disponibles, ["correo"]) && igual(r.noDisponibles, ["envio_tienda"]) && !r.respaldo, "Córdoba: envío de la tienda no llega, correo sí")
  r = L.metodosParaComprador(ambos, { zonaTienda: null, zonaCorreo: 2 })
  ok(igual(r.disponibles, ["coordinar"]) && igual(r.noDisponibles, ["envio_tienda", "correo"]) && r.respaldo,
    "Pringles con zona 2 sin precio: ninguno llega, respaldo")
  r = L.metodosParaComprador(t(["correo"], { correo_1: 100 }), {})
  ok(igual(r.disponibles, ["correo"]), "sin dirección todavía: el correo se muestra")

  const env = (extra) => calcularEnvio({ vendedor: ambos, hayDireccion: true, ...extra })
  r = env({ metodoEnvio: "correo", zonaCorreo: 4, codigoPostalOk: true })
  ok(r.costo === 9000 && r.zona === 4 && r.metodo === "correo", "correo zona 4: $9000, zona 4 para pedidos.zona_envio")
  ok(env({ metodoEnvio: "correo", zonaCorreo: 4, codigoPostalOk: false }).codigo === "FALTA_CODIGO_POSTAL", "sin código postal: rechazo")
  ok(env({ metodoEnvio: "correo", zonaCorreo: undefined, codigoPostalOk: true }).codigo === "SIN_ZONA", "sin zona calculada por el servidor: rechazo")
  ok(env({ metodoEnvio: "correo", zonaCorreo: 2, codigoPostalOk: true }).codigo === "ZONA_SIN_COSTO", "zona sin precio: no envía")
  ok(env({ metodoEnvio: "envio_tienda", zonaTienda: null, zonaCorreo: 4 }).codigo === "ZONA_SIN_COSTO", "envío de la tienda a más de 20 km: no llega")
  ok(env({ metodoEnvio: "coordinar", zonaTienda: null, zonaCorreo: 2 }).metodo === "coordinar", "respaldo comprobado (ninguno llega): vale")
  ok(env({ metodoEnvio: "coordinar", zonaTienda: null, zonaCorreo: 4 }).codigo === "METODO_INVALIDO", "respaldo con el correo disponible: no vale")
}

console.log("\n11. zonasPara: las dos zonas y el registro")
{
  const registro = []
  const admin = { from: () => ({ insert: async (fila) => { registro.push(fila); return { error: null } } }) }
  const avisos = console.warn
  console.warn = () => {}
  const tienda = { id: 15, latitud: CIUDADES.bahia.lat, longitud: CIUDADES.bahia.lng }
  const metodos = ["envio_tienda", "correo"]
  let z = await zonasPara({ admin, vendedor: tienda, direccion: { id: 1, ...CIUDADES["Punta Alta"] }, origen: "cotizar", metodos })
  ok(z.envio_tienda.zona === null && z.envio_tienda.motivo === "lejos" && z.correo.zona === 1 && registro.length === 0,
    "Punta Alta: envío de la tienda lejos (no se registra), correo zona 1")
  z = await zonasPara({ admin, vendedor: tienda, direccion: { id: 2, lat: null, lng: null }, origen: "crear", metodos })
  ok(z.envio_tienda.zona === null && z.correo.zona === null, "sin punto: las dos null")
  ok(igual(registro.map((r) => [r.metodo, r.motivo, r.origen]), [["envio_tienda", "direccion_sin_punto", "crear"], ["correo", "direccion_sin_punto", "crear"]]),
    "y una fila por método, con el motivo")
  z = await zonasPara({ admin, vendedor: tienda, direccion: { id: 1, ...CIUDADES.Mendoza }, origen: "cotizar", metodos: ["correo"] })
  ok(z.correo.zona === 4 && z.envio_tienda === undefined, "sólo los métodos pedidos")
  console.warn = avisos
}

console.log("\n12. Direcciones: reglas del formulario")
{
  const base = { enBahia: true, calle: "Alsina", numero: "235", telefono: "291", codigoPostal: "8000", barrioId: 1, lat: -38.71, lng: -62.26 }
  ok(D.errorDireccion(base) === null, "Bahía completa: vale")
  ok(/barrio/.test(D.errorDireccion({ ...base, barrioId: null })), "Bahía sin barrio: no")
  ok(/código postal/.test(D.errorDireccion({ ...base, codigoPostal: "" })), "sin código postal: no (también en Bahía)")
  ok(/mapa/.test(D.errorDireccion({ ...base, lat: null })), "sin punto: no")
  const otra = { ...base, enBahia: false, barrioId: null, ciudad: "Punta Alta", provincia: "Buenos Aires", codigoPostal: "b8109 abc", lat: -38.88, lng: -62.07 }
  ok(D.errorDireccion(otra) === null, "otra ciudad sin barrio: vale")
  ok(/provincia/.test(D.errorDireccion({ ...otra, provincia: "" })), "otra ciudad sin provincia: no")
  ok(/ciudad/.test(D.errorDireccion({ ...otra, ciudad: " " })), "otra ciudad sin ciudad: no")
  ok(/Sí, en Bahía Blanca/.test(D.errorDireccion({ ...otra, ciudad: "bahia  blanca" })), "'otra ciudad' que es Bahía: le pide elegir Sí")
  ok(/fuera de Argentina/.test(D.errorDireccion({ ...otra, lat: 40.4, lng: -3.7 })), "un punto en Madrid: no")
  ok(D.esDeBahia({ barrio_id: 3 }) && !D.esDeBahia({ barrio_id: null }), "es de Bahía = tiene barrio")
  ok(D.ciudadProvinciaCodigo({ ciudad: "Punta Alta", provincia: "Buenos Aires", codigo_postal: "B8109ABC" }) === "Punta Alta, Buenos Aires (B8109ABC)", "texto de otra ciudad")
  ok(D.ciudadProvinciaCodigo({ ciudad: "Bahía Blanca", provincia: "Buenos Aires", codigo_postal: "8000" }) === "Bahía Blanca (8000)", "texto de Bahía")
  ok(D.ciudadProvinciaCodigo({ calle: "X" }) === "", "dirección vieja sin ciudad: nada")
}

console.log("\n12b. La búsqueda cayó en otra ciudad (respuestas reales de Nominatim, 4/10/2026)")
{
  const MENDOZA = { city: "Ciudad de Mendoza", county: "Sección 5ª Residencial Sur", state_district: "Departamento Capital", state: "Mendoza", postcode: "5500" }
  const SAN_MARTIN_MZA = { town: "Distrito Ciudad de San Martín", state_district: "Departamento San Martín", state: "Mendoza", postcode: "5570" }
  const GODOY_CRUZ = { city: "Distrito Ciudad de Godoy Cruz", state: "Mendoza", postcode: "5501" }
  const SAN_MARTIN_BA = { town: "Ciudad del Libertador General San Martín", state_district: "Partido de General San Martín", state: "Buenos Aires", postcode: "B1650LQP" }
  const PUNTA_ALTA = { town: "Punta Alta", county: "Cuartel VI", state_district: "Partido de Coronel de Marina Leonardo Rosales", state: "Buenos Aires", postcode: "8109" }

  ok(D.avisoLugar({ ciudad: "Mendoza", provincia: "Mendoza" }, MENDOZA) === null, "Mendoza → Ciudad de Mendoza: coincide")
  ok(D.avisoLugar({ ciudad: "Mendoza", provincia: "Mendoza" }, SAN_MARTIN_MZA) ===
    "Encontramos esta dirección en San Martín, no en Mendoza. Revisá los datos o mové el pin hasta tu casa.",
    "Mendoza → San Martín (lo que pasaba sin código postal): avisa")
  ok(/en Godoy Cruz, no en Mendoza/.test(D.avisoLugar({ ciudad: "Mendoza", provincia: "Mendoza" }, GODOY_CRUZ)), "Mendoza → Godoy Cruz: avisa")
  ok(D.avisoLugar({ ciudad: "Punta Alta", provincia: "Buenos Aires" }, PUNTA_ALTA) === null, "Punta Alta: coincide")
  ok(D.avisoLugar({ ciudad: "San Martín", provincia: "Mendoza" }, SAN_MARTIN_MZA) === null, "San Martín (Mendoza): coincide")
  ok(D.avisoLugar({ ciudad: "san martin", provincia: "Buenos Aires" }, SAN_MARTIN_BA) === null, "San Martín (Buenos Aires), sin acentos: coincide")
  ok(D.avisoLugar({ ciudad: "San Martín", provincia: "Buenos Aires" }, SAN_MARTIN_MZA) ===
    "Encontramos esta dirección en San Martín, Mendoza, no en San Martín, Buenos Aires. Revisá los datos o mové el pin hasta tu casa.",
    "mismo nombre, otra provincia: avisa con las provincias")
  ok(/no en Mar/.test(D.avisoLugar({ ciudad: "Mar", provincia: "Buenos Aires" }, PUNTA_ALTA) || ""), "una palabra suelta no alcanza para coincidir")
  ok(D.avisoLugar({ ciudad: "Alta", provincia: "Buenos Aires" }, PUNTA_ALTA) === null, "…pero una frase entera dentro del nombre sí (Alta ⊂ Punta Alta)")
  ok(D.avisoLugar({ ciudad: "Mendoza", provincia: "Mendoza" }, null) === null, "sin datos del lugar: no avisa")
}

console.log("\n13. Seguimiento y textos")
{
  ok(L.validarSeguimiento({ empresa: "andreani", numero: "  360 000 " }).campos?.envio_seguimiento === "360 000", "limpia el número")
  ok(L.validarSeguimiento({ empresa: "otra", otra: "Vía Cargo", numero: "1" }).campos?.envio_empresa_otra === "Vía Cargo", "otra con nombre")
  ok(!L.validarSeguimiento({ empresa: "otra", numero: "1" }).ok, "otra sin nombre: no")
  ok(L.validarSeguimiento({ empresa: "oca", otra: "ignorado", numero: "1" }).campos?.envio_empresa_otra === null, "con OCA el nombre no se guarda")
  ok(!L.validarSeguimiento({ empresa: "dhl", numero: "1" }).ok && !L.validarSeguimiento({ empresa: "oca", numero: " " }).ok, "empresa desconocida o sin número: no")
  const s = L.seguimientoDe({ envio_empresa: "correo_argentino", envio_seguimiento: "CP123AR" })
  ok(s.empresa === "Correo Argentino" && s.url.startsWith("https://www.correoargentino.com.ar/"), "Correo Argentino con su página")
  ok(L.seguimientoDe({ envio_empresa: "otra", envio_empresa_otra: "Vía Cargo", envio_seguimiento: "1" }).url === null, "otra: sin link")
  ok(L.seguimientoDe({}) === null, "sin seguimiento: nada")
  ok(L.grupoEntrega("correo") === "correo" && L.grupoEntrega("envio_tienda") === "envio", "el correo tiene sus propios textos")
  ok(!L.validarEntrega({ metodos: ["correo"], costos: { correo_1: 100 }, tienePunto: false }).ok, "el correo necesita el punto de la tienda")
  ok(L.validarEntrega({ metodos: ["correo"], costos: { correo_1: 100 }, tienePunto: true }).ok, "con punto y un precio: vale")
}

console.log(fallas === 0 ? "\nTODO OK" : `\n${fallas} FALLAS`)
// exitCode y no exit(): con el cargador del alias registrado, exit() corta un hilo
// a mitad de cerrarse y Node avisa con un "Assertion failed" en Windows.
process.exitCode = fallas ? 1 : 0
